# Generated by Django 4.0.3 on 2022-04-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_student_branch_remove_student_semester_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
    ]
