# Generated by Django 4.0.3 on 2022-04-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_section_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twoFactor',
            field=models.BooleanField(default=False),
        ),
    ]
