# Generated by Django 4.0.3 on 2022-04-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_module', '0003_assignment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignmentans',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
