# Generated by Django 4.0.3 on 2022-04-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_module', '0004_studentassignmentans_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submissions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
