# Generated by Django 4.0.3 on 2022-04-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_module', '0005_assignment_submissions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assignmentassigner',
            table='assignment_assigner',
        ),
    ]
